version: "3.9"

services:
  postgres:
    image: postgres:14-bullseye
    container_name: enigmanations_postgres_container
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5430:5432
    networks:
      - app_network

  api:
    container_name: enigmanations_api_container
    tty: true
    build: .
    environment:
      - ENV=production
      - DB_HOST=host.docker.internal
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5430
      - DB_PARAMS=${DB_PARAMS}
      - APP_HOST=localhost
      - APP_PORT=8080
      - BCRYPT_SALT=${BCRYPT_SALT}
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - database_postgres:/var/lib/postgresql/data
    depends_on:
      - postgres
    networks:
      - app_network

volumes:
  api:
  database_postgres:

networks:
  app_network:
    external: true
