package staff

type Staff struct {
	ID          int    `json:"id"`
	PhoneNumber string `json:"phone_number"`
	Name        string `json:"name"`
	Password    string `json:"password"`
}

type Country struct {
	Name string
	Code string
}

var Countries = []Country{
	{Name: "Afghanistan", Code: "+93"},
	{Name: "Albania", Code: "+355"},
	{Name: "Algeria", Code: "+213"},
	{Name: "Andorra", Code: "+376"},
	{Name: "Angola", Code: "+244"},
	{Name: "Antigua and Barbuda", Code: "+1-268"},
	{Name: "Argentina", Code: "+54"},
	{Name: "Armenia", Code: "+374"},
	{Name: "Australia", Code: "+61"},
	{Name: "Austria", Code: "+43"},
	{Name: "Azerbaijan", Code: "+994"},
	{Name: "Bahamas", Code: "+1-242"},
	{Name: "Bahrain", Code: "+973"},
	{Name: "Bangladesh", Code: "+880"},
	{Name: "Barbados", Code: "+1-246"},
	{Name: "Belarus", Code: "+375"},
	{Name: "Belgium", Code: "+32"},
	{Name: "Belize", Code: "+501"},
	{Name: "Benin", Code: "+229"},
	{Name: "Bhutan", Code: "+975"},
	{Name: "Bolivia", Code: "+591"},
	{Name: "Bosnia and Herzegovina", Code: "+387"},
	{Name: "Botswana", Code: "+267"},
	{Name: "Brazil", Code: "+55"},
	{Name: "Brunei", Code: "+673"},
	{Name: "Bulgaria", Code: "+359"},
	{Name: "Burkina Faso", Code: "+226"},
	{Name: "Burundi", Code: "+257"},
	{Name: "Cabo Verde", Code: "+238"},
	{Name: "Cambodia", Code: "+855"},
	{Name: "Cameroon", Code: "+237"},
	{Name: "Canada", Code: "+1"},
	{Name: "Central African Republic", Code: "+236"},
	{Name: "Chad", Code: "+235"},
	{Name: "Chile", Code: "+56"},
	{Name: "China", Code: "+86"},
	{Name: "Colombia", Code: "+57"},
	{Name: "Comoros", Code: "+269"},
	{Name: "Congo", Code: "+242"},
	{Name: "Costa Rica", Code: "+506"},
	{Name: "Croatia", Code: "+385"},
	{Name: "Cuba", Code: "+53"},
	{Name: "Cyprus", Code: "+357"},
	{Name: "Czech Republic", Code: "+420"},
	{Name: "Denmark", Code: "+45"},
	{Name: "Djibouti", Code: "+253"},
	{Name: "Dominica", Code: "+1-767"},
	{Name: "Dominican Republic", Code: "+1-809"},
	{Name: "East Timor", Code: "+670"},
	{Name: "Ecuador", Code: "+593"},
	{Name: "Egypt", Code: "+20"},
	{Name: "El Salvador", Code: "+503"},
	{Name: "Equatorial Guinea", Code: "+240"},
	{Name: "Eritrea", Code: "+291"},
	{Name: "Estonia", Code: "+372"},
	{Name: "Eswatini", Code: "+268"},
	{Name: "Ethiopia", Code: "+251"},
	{Name: "Fiji", Code: "+679"},
	{Name: "Finland", Code: "+358"},
	{Name: "France", Code: "+33"},
	{Name: "Gabon", Code: "+241"},
	{Name: "Gambia", Code: "+220"},
	{Name: "Georgia", Code: "+995"},
	{Name: "Germany", Code: "+49"},
	{Name: "Ghana", Code: "+233"},
	{Name: "Greece", Code: "+30"},
	{Name: "Grenada", Code: "+1-473"},
	{Name: "Guatemala", Code: "+502"},
	{Name: "Guinea", Code: "+224"},
	{Name: "Guinea-Bissau", Code: "+245"},
	{Name: "Guyana", Code: "+592"},
	{Name: "Haiti", Code: "+509"},
	{Name: "Honduras", Code: "+504"},
	{Name: "Hungary", Code: "+36"},
	{Name: "Iceland", Code: "+354"},
	{Name: "India", Code: "+91"},
	{Name: "Indonesia", Code: "+62"},
	{Name: "Iran", Code: "+98"},
	{Name: "Iraq", Code: "+964"},
	{Name: "Ireland", Code: "+353"},
	{Name: "Israel", Code: "+972"},
	{Name: "Italy", Code: "+39"},
	{Name: "Jamaica", Code: "+1-876"},
	{Name: "Japan", Code: "+81"},
	{Name: "Jordan", Code: "+962"},
	{Name: "Kazakhstan", Code: "+7"},
	{Name: "Kenya", Code: "+254"},
	{Name: "Kiribati", Code: "+686"},
	{Name: "Korea, North", Code: "+850"},
	{Name: "Korea, South", Code: "+82"},
	{Name: "Kosovo", Code: "+383"},
	{Name: "Kuwait", Code: "+965"},
	{Name: "Kyrgyzstan", Code: "+996"},
	{Name: "Laos", Code: "+856"},
	{Name: "Latvia", Code: "+371"},
	{Name: "Lebanon", Code: "+961"},
	{Name: "Lesotho", Code: "+266"},
	{Name: "Liberia", Code: "+231"},
	{Name: "Libya", Code: "+218"},
	{Name: "Liechtenstein", Code: "+423"},
	{Name: "Lithuania", Code: "+370"},
	{Name: "Luxembourg", Code: "+352"},
	{Name: "Madagascar", Code: "+261"},
	{Name: "Malawi", Code: "+265"},
	{Name: "Malaysia", Code: "+60"},
	{Name: "Maldives", Code: "+960"},
	{Name: "Mali", Code: "+223"},
	{Name: "Malta", Code: "+356"},
	{Name: "Marshall Islands", Code: "+692"},
	{Name: "Mauritania", Code: "+222"},
	{Name: "Mauritius", Code: "+230"},
	{Name: "Mexico", Code: "+52"},
	{Name: "Micronesia", Code: "+691"},
	{Name: "Moldova", Code: "+373"},
	{Name: "Monaco", Code: "+377"},
	{Name: "Mongolia", Code: "+976"},
	{Name: "Montenegro", Code: "+382"},
	{Name: "Morocco", Code: "+212"},
	{Name: "Mozambique", Code: "+258"},
	{Name: "Myanmar", Code: "+95"},
	{Name: "Namibia", Code: "+264"},
	{Name: "Nauru", Code: "+674"},
	{Name: "Nepal", Code: "+977"},
	{Name: "Netherlands", Code: "+31"},
	{Name: "New Zealand", Code: "+64"},
	{Name: "Nicaragua", Code: "+505"},
	{Name: "Niger", Code: "+227"},
	{Name: "Nigeria", Code: "+234"},
	{Name: "North Macedonia", Code: "+389"},
	{Name: "Norway", Code: "+47"},
	{Name: "Oman", Code: "+968"},
	{Name: "Pakistan", Code: "+92"},
	{Name: "Palau", Code: "+680"},
	{Name: "Palestine", Code: "+970"},
	{Name: "Panama", Code: "+507"},
	{Name: "Papua New Guinea", Code: "+675"},
	{Name: "Paraguay", Code: "+595"},
	{Name: "Peru", Code: "+51"},
	{Name: "Philippines", Code: "+63"},
	{Name: "Poland", Code: "+48"},
	{Name: "Portugal", Code: "+351"},
	{Name: "Qatar", Code: "+974"},
	{Name: "Romania", Code: "+40"},
	{Name: "Russia", Code: "+7"},
	{Name: "Rwanda", Code: "+250"},
	{Name: "Saint Kitts and Nevis", Code: "+1-869"},
	{Name: "Saint Lucia", Code: "+1-758"},
	{Name: "Saint Vincent and the Grenadines", Code: "+1-784"},
	{Name: "Samoa", Code: "+685"},
	{Name: "San Marino", Code: "+378"},
	{Name: "Sao Tome and Principe", Code: "+239"},
	{Name: "Saudi Arabia", Code: "+966"},
	{Name: "Senegal", Code: "+221"},
	{Name: "Serbia", Code: "+381"},
	{Name: "Seychelles", Code: "+248"},
	{Name: "Sierra Leone", Code: "+232"},
	{Name: "Singapore", Code: "+65"},
	{Name: "Slovakia", Code: "+421"},
	{Name: "Slovenia", Code: "+386"},
	{Name: "Solomon Islands", Code: "+677"},
	{Name: "Somalia", Code: "+252"},
	{Name: "South Africa", Code: "+27"},
	{Name: "South Sudan", Code: "+211"},
	{Name: "Spain", Code: "+34"},
	{Name: "Sri Lanka", Code: "+94"},
	{Name: "Sudan", Code: "+249"},
	{Name: "Suriname", Code: "+597"},
	{Name: "Sweden", Code: "+46"},
	{Name: "Switzerland", Code: "+41"},
	{Name: "Syria", Code: "+963"},
	{Name: "Taiwan", Code: "+886"},
	{Name: "Tajikistan", Code: "+992"},
	{Name: "Tanzania", Code: "+255"},
	{Name: "Thailand", Code: "+66"},
	{Name: "Togo", Code: "+228"},
	{Name: "Tonga", Code: "+676"},
	{Name: "Trinidad and Tobago", Code: "+1-868"},
	{Name: "Tunisia", Code: "+216"},
	{Name: "Turkey", Code: "+90"},
	{Name: "Turkmenistan", Code: "+993"},
	{Name: "Tuvalu", Code: "+688"},
	{Name: "Uganda", Code: "+256"},
	{Name: "Ukraine", Code: "+380"},
	{Name: "United Arab Emirates", Code: "+971"},
	{Name: "United Kingdom", Code: "+44"},
	{Name: "United States", Code: "+1"},
	{Name: "Uruguay", Code: "+598"},
	{Name: "Uzbekistan", Code: "+998"},
	{Name: "Vanuatu", Code: "+678"},
	{Name: "Vatican City", Code: "+379"},
	{Name: "Venezuela", Code: "+58"},
	{Name: "Vietnam", Code: "+84"},
	{Name: "Yemen", Code: "+967"},
	{Name: "Zambia", Code: "+260"},
	{Name: "Zimbabwe", Code: "+263"},
}
